spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@10.191.66.31:1521:orcl
    username: cldmp_dev
    password: p@ssword

mybatis:
  type-aliases-package: com.wonder.entity
  mapper-locations: classpath:mapper/*.xml